%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.20.3 on {{2016,6,22},{14,32,44}}

-ifndef(mesos_state_overlay_pb).
-define(mesos_state_overlay_pb, true).

-define(mesos_state_overlay_pb_gpb_version, "3.20.3").

-ifndef('MESOS_STATE_AGENTOVERLAYINFO.STATE_PB_H').
-define('MESOS_STATE_AGENTOVERLAYINFO.STATE_PB_H', true).
-record('mesos_state_agentoverlayinfo.state',
        {status                 :: 'STATUS_INVALID' | 'STATUS_OK' | 'STATUS_FAILED', % = 1, enum AgentOverlayInfo.State.Status
         error                  :: binary() | undefined % = 2
        }).
-endif.

-ifndef('MESOS_STATE_VXLANINFO_PB_H').
-define('MESOS_STATE_VXLANINFO_PB_H', true).
-record(mesos_state_vxlaninfo,
        {vni                    :: non_neg_integer(), % = 1, 32 bits
         vtep_name              :: binary(),        % = 2
         vtep_ip                :: binary(),        % = 3
         vtep_mac               :: binary()         % = 4
        }).
-endif.

-ifndef('MESOS_STATE_BACKENDINFO_PB_H').
-define('MESOS_STATE_BACKENDINFO_PB_H', true).
-record(mesos_state_backendinfo,
        {vxlan                  :: #mesos_state_vxlaninfo{} | undefined % = 1
        }).
-endif.

-ifndef('MESOS_STATE_BRIDGEINFO_PB_H').
-define('MESOS_STATE_BRIDGEINFO_PB_H', true).
-record(mesos_state_bridgeinfo,
        {name                   :: binary(),        % = 1
         ip                     :: binary()         % = 2
        }).
-endif.

-ifndef('MESOS_STATE_OVERLAYINFO_PB_H').
-define('MESOS_STATE_OVERLAYINFO_PB_H', true).
-record(mesos_state_overlayinfo,
        {name                   :: binary(),        % = 1
         subnet                 :: binary(),        % = 2
         prefix                 :: non_neg_integer() % = 3, 32 bits
        }).
-endif.

-ifndef('MESOS_STATE_AGENTOVERLAYINFO_PB_H').
-define('MESOS_STATE_AGENTOVERLAYINFO_PB_H', true).
-record(mesos_state_agentoverlayinfo,
        {info                   :: #mesos_state_overlayinfo{}, % = 1
         subnet                 :: binary(),        % = 2
         mesos_bridge           :: #mesos_state_bridgeinfo{} | undefined, % = 3
         docker_bridge          :: #mesos_state_bridgeinfo{} | undefined, % = 4
         backend                :: #mesos_state_backendinfo{}, % = 5
         state                  :: #'mesos_state_agentoverlayinfo.state'{} | undefined % = 6
        }).
-endif.

-ifndef('MESOS_STATE_AGENTINFO_PB_H').
-define('MESOS_STATE_AGENTINFO_PB_H', true).
-record(mesos_state_agentinfo,
        {ip                     :: binary(),        % = 1
         overlays = []          :: [#mesos_state_agentoverlayinfo{}] % = 2
        }).
-endif.

-ifndef('MESOS_STATE_STATE_PB_H').
-define('MESOS_STATE_STATE_PB_H', true).
-record(mesos_state_state,
        {overlays = []          :: [#mesos_state_overlayinfo{}], % = 1
         agents = []            :: [#mesos_state_agentinfo{}] % = 2
        }).
-endif.

-ifndef('MESOS_STATE_NETWORKCONFIG_PB_H').
-define('MESOS_STATE_NETWORKCONFIG_PB_H', true).
-record(mesos_state_networkconfig,
        {vtep_subnet            :: binary(),        % = 1
         vtep_mac_oui           :: binary(),        % = 2
         overlays = []          :: [#mesos_state_overlayinfo{}] % = 3
        }).
-endif.

-endif.
